##
# @file blockchain.py
# @author Tom Rose
#
# @brief
#   Simulates the invocation of a blockchain smart contract for ZKP-OTP verification and logs authentication events
#
# @details
#   - Anonymizes vehicle IDs using hashing before logging
#   - Simulates a smart contract call and logs the event with vehicle hash, timestamp, and authentication status
#   - Returns the outcome to mimic infrastructure access control
##

## Imports
# Libraries
import hashlib

# Classes and functions
from settings import DEBUG_MODE as DEFAULT_DEBUG_MODE

## @var DEBUG_MODE
## @brief Global variable to control debug output
DEBUG_MODE = DEFAULT_DEBUG_MODE


##
# @brief Enable or disable debug mode for detailed output
#
# @param enabled True to enable debug mode, False to disable
#
# @details
#   Steps:
#     1. Set the global DEBUG_MODE variable to the provided value
##
def set_debug_mode(enabled):
    
    # DEBUG_MODE - Global variable to control debug output
    global DEBUG_MODE
    DEBUG_MODE = enabled


##
# @brief Simulate invoking a smart contract for ZKP-OTP verification and logging the event
#
# @param vehicle_id The unique identifier for the vehicle
# @param zkp_proof The zero-knowledge proof generated by the vehicle
# @param timestamp The timestamp associated with the OTP
# @param verification_result The result of RSU verification (True if authenticated)
#
# @return The outcome of the simulated blockchain verification (same as input verification_result)
#
# @details
#   Steps:
#     1. Hash the vehicle_id to anonymize it for blockchain logging
#     2. Print a message simulating the smart contract call with anonymized vehicle ID (if DEBUG_MODE)
#     3. Create a log entry dictionary with anonymized vehicle hash, timestamp, and authentication status
#     4. Print the simulated blockchain event log (if DEBUG_MODE)
#     5. Return the outcome to simulate the infrastructure's access decision
#
# @note
#   - The zkp_proof is not used in this simulation; it serves as a placeholder for future integration
##
def simulate_blockchain_verification(vehicle_id, zkp_proof, timestamp, verification_result):
    
    # anonymized_id - Hash the vehicle_id to anonymize it for blockchain logging and take the first 10 characters
    anonymized_id = hashlib.sha256(vehicle_id.encode()).hexdigest()[:10]
    
    # If debug mode is enabled, print a message simulating the smart contract call
    if DEBUG_MODE:
        print(f"[Blockchain] Verifying ZKP-OTP proof for anonymized vehicle ID: {anonymized_id}...\n")
    
    # log_entry - Create a log entry dictionary with anonymized vehicle hash, timestamp, and authentication status
    log_entry = {
        # Full hash for record
        "vehicle_hash": hashlib.sha256(vehicle_id.encode()).hexdigest(),
        # Timestamp of the authentication attempt
        "timestamp": timestamp,
        # Whether authentication succeeded
        "authenticated": verification_result
    }
    
    # If debug mode is enabled, print the simulated blockchain event log
    if DEBUG_MODE:
        print(f"[Blockchain] Event logged: {log_entry}\n")
        
    # Return the outcome to simulate the infrastructure's access decision
    return verification_result


## Test the blockchain verification simulation
if __name__ == "__main__":
    
    ## @var vehicle_id
    ## @brief Set a dummy vehicle ID
    vehicle_id = "TEST_VEHICLE"
    
    ## @var zkp_proof
    ## @brief Set a dummy ZKP proof
    zkp_proof = "dummy_zkp_proof"
    
    ## @var timestamp
    ## @brief Set a dummy timestamp
    timestamp = 1234567890
    
    ## @var verification_result
    ## @brief Set a dummy verification result (True for authenticated)
    verification_result = True
    
    ## @var result
    ## @brief Simulate the blockchain verification
    result = simulate_blockchain_verification(vehicle_id, zkp_proof, timestamp, verification_result)
    
    # Print the result of the simulation
    print(f"[Blockchain] Simulated verification result: {result}")

