##
# @file settings.py
# @author Tom Rose
#
# @brief
#   Centralizes configuration settings for the project, including debug flags,
#   file paths, network settings, and cleanup configuration.
#
# @details
#   - Provides global debug settings for all modules
#   - Defines path configuration for SUMO and ZoKrates files
#   - Specifies network ports for various services
#   - Lists files to clean up for ZoKrates
##

import os

## Base Directories
# Project base directory
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# Directory for SUMO files
SUMO_DIR = os.path.join(BASE_DIR, "sumo")

# Directory for ZoKrates files
ZOKRATES_DIR = os.path.join(BASE_DIR, "zokrates")

## Debug Settings
# Global debug mode flag
DEBUG_MODE = False

## SUMO Settings
# SUMO tools path from environment or default
SUMO_TOOLS_PATH = os.getenv("SUMO_TOOLS_PATH", "/home/admin/sumo/tools")

# Path to basic SUMO network file
SUMO_SIMPLE_NET_FILE = os.path.join(SUMO_DIR, "simple.net.xml")

# Path to SUMO configuration file for 3x3 city block
SUMO_CITY_CONFIG_FILE = os.path.join(SUMO_DIR, "3x3 city block 1", "threebythreecityblock1.sumocfg")

# Path to SUMO intersection configuration
SUMO_INTERSECTION_CONFIG_FILE = os.path.join(SUMO_DIR, "Intersection 1", "intersection1.sumocfg")

## Network Settings
# TraCI ports for SUMO connections
SUMO_PORT_BASIC = 8813
SUMO_PORT_CONFIG = 8814
SUMO_PORT_DATA = 8815
SUMO_PORT_DATA_CONFIG = 8816

## ZoKrates Settings
# Path to ZoKrates dummy circuit
ZOKRATES_DUMMY_CIRCUIT = os.path.join(ZOKRATES_DIR, "dummy.zok")

# Path to ZoKrates authentication circuit
ZOKRATES_AUTH_CIRCUIT = os.path.join(ZOKRATES_DIR, "auth.zok")

# List of files typically generated by ZoKrates commands to clean up
ZOKRATES_CLEANUP_FILES = [
    "out",
    "out.r1cs",
    "out.wtns",
    "proving.key",
    "verification.key",
    "witness",
    "proof.json",
    "abi.json"
]

## Blockchain Settings
# Default provider URL
BLOCKCHAIN_PROVIDER_URL = "http://127.0.0.1:8545"
