##
# @file zkp.py
# @author Tom Rose
#
# @brief
#   Provides functions for generating zero-knowledge proofs (ZKPs) for authentication workflows.
#   Supports both simulated (hash-based) and real (ZoKrates CLI) ZKP generation and verification.
#
# @details
#   - Simulates ZKP generation by hashing OTP and timestamp for rapid prototyping and testing.
#   - Provides wrapper functions to interact with ZoKrates CLI for real ZKP workflows.
#   - Designed to be used by Vehicle and RSU classes for proof generation and verification.
##

import hashlib

# Import ZoKrates interface functions for future use
from zokrates_interface import (
    run_zokrates_compile,
    run_zokrates_setup,
    run_zokrates_compute_witness,
    run_zokrates_generate_proof,
    run_zokrates_verify
)

##
# @brief Simulate ZoKrates proof generation (hash-based).
#
# @param otp The one-time password generated by the vehicle.
# @param timestamp The timestamp used in OTP generation.
# @return Simulated ZKP proof (hash of OTP and timestamp).
#
# @details
#   Steps:
#     1. Concatenate OTP and timestamp.
#     2. Hash the result using SHA-256.
#     3. Return the hash as proof.
##
def generate_zkp_proof_simulated(otp, timestamp):
    # Concatenate OTP and timestamp as a string, then encode to bytes
    combined = f"{otp}{timestamp}".encode()
    # Hash the combined bytes using SHA-256
    proof = hashlib.sha256(combined).hexdigest()
    # Return the resulting hash as the simulated ZKP proof
    return proof

##
# @brief Generate a real ZKP proof using the ZoKrates CLI interface.
#
# @param circuit_path Path to the ZoKrates .zok circuit file.
# @param otp The one-time password generated by the vehicle.
# @param timestamp The timestamp used in OTP generation.
# @return True if proof is valid, False otherwise.
#
# @details
#   Steps:
#     1. Compile the ZoKrates circuit.
#     2. Run setup to generate keys.
#     3. Compute witness.
#     4. Generate proof.
#     5. Verify proof and return result.
##
def generate_zkp_proof_real(circuit_path, otp, timestamp):
    # Compile the ZoKrates circuit; return False if compilation fails
    if not run_zokrates_compile(circuit_path):
        return False
    # Run ZoKrates setup to generate keys; return False if setup fails
    if not run_zokrates_setup():
        return False
    # Prepare the arguments as strings for the witness computation
    args = [str(otp), str(timestamp)]
    # Compute the witness; return False if this step fails
    if not run_zokrates_compute_witness(args):
        return False
    # Generate the proof; return False if this step fails
    if not run_zokrates_generate_proof():
        return False
    # Verify the proof and return the result (True if valid, False otherwise)
    return run_zokrates_verify()

# Do NOT alias generate_zkp_proof to simulated version.
# Now must explicitly choose generate_zkp_proof_simulated or generate_zkp_proof_real.

if __name__ == "__main__":
    ## @test Simple test for ZKP proof generation
    otp = "testotp"
    timestamp = 1234567890
    proof = generate_zkp_proof_simulated(otp, timestamp)
    print(f"[ZKP] Simulated proof for otp='{otp}', timestamp={timestamp}: {proof}")

